### PR TITLE
Origin/related videos component

### LINKED ISSUE #11: YouTube Data to Front End
- [x] Decide what information is crucial to pass to the Front End to develop related videos per article
- [x] Format into a data type that can be interated over for each video

### LINKED ISSUE #12: Articles with Related Videos
As an visitor 
when I visit an article show page
I see at least three YouTube videos available
that are related to the material in the article.

- [x] Youtube API Service
- [x] Data Formatted/Passed to Front End
- [x] Video Player Renders and Plays

### LINKED ISSUE #16: Youtube API calling too much
**Describe the bug**
 Based on where the API is called and other features such as instant-click the api is getting bombarded rapidly.
**To Reproduce**

Load any page that can contain a link to an article
Mouse over the article and check the API console

**Expected behavior**

Should only make the call when one that article's page

**Screenshots**

Screen Shot 2020-05-14 at 9 52 51 AM
Screen Shot 2020-05-13 at 4 58 28 PM

**Additional context**

Ideas for resolution: Cache the data based on article id.

### LINKED ISSUE #17: Some articles aren't getting videos while others are
**Describe the bug**
Certain articles won't render videos while some will

**Expected behavior**

Every article should have three videos

**Additional context**

Is the an error coming for Youtube API, or maybe it cached without them and now isn't trying again.

### PR DESCRIPTION
**Pull request by rcallen89**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds the video component to the article show page.  Video component takes the videoId from the instance variable @related_videos.  This information is also cached for 12 hours to prevent additional api calls.  InstantClick was modified to on mousedown to cut down on api calls as well.

Hard coded article seeds were added for easier local testing.

This will fail Travis CI

- [ ] yes
- [x] no, because they aren't needed - Tests where modified from the original API service to match new keys
- [ ] no, because I need help

### CODE REVIEW

File: app/assets/javascripts/base.js.erb [hunk 1]
```diff
@@ -673,7 +673,7 @@ var instantClick
     InstantClick.on('change', function() {
       initializePage();
     });
-    InstantClick.init();
+    InstantClick.init('mousedown');
```
Comment (rcallen89) [inline app/assets/javascripts/base.js.erb:676]: Change Instantclick to be on mousedown instead of the default of mouse over

File: app/assets/stylesheets/article-show.scss [hunk 2]
```diff
@@ -1,6 +1,16 @@
...
+.related-videos {
+  display: flex;
+  justify-content: space-around;
+  width: 100%;
+
+  iframe {
+    width: 30%;
+  }
+}
+
```
Comment (rcallen89) [inline app/assets/stylesheets/article-show.scss:13]: Original Comment from @jonathan-tschida - 
This is just some basic styling, obviously could use a little more work.

File: app/controllers/stories_controller.rb [hunk 3]
```diff
@@ -220,6 +220,9 @@ def handle_article_show
     redirect_if_show_view_param
     return if performed?
 
+    Rails.cache.fetch("#{@article.id}-related-vidoes", expires_in: 12.hours) do
+      @related_videos = YouTubeService.video_info(@article.cached_tag_list_array)
+    end
```
Comment (rcallen89) [inline app/controllers/stories_controller.rb:225]: Cache the Videos information to save on api calls

File: app/decorators/article_decorator.rb [hunk 4]
```diff
@@ -53,10 +53,6 @@ def published_at_int
     published_at.to_i
   end
 
-  def related_videos
-    YouTubeService.video_info(cached_tag_list_array)
-  end
-
```
Comment (rcallen89) [inline app/decorators/article_decorator.rb:59]: Moved this method to the stories controller

File: app/javascript/packs/homePage.jsx [hunk 5]
```diff
@@ -130,4 +130,4 @@ InstantClick.on('receive', (address, body, title) => {
     title,
   };
 });
-InstantClick.init();
+InstantClick.init('mousedown');
```
Comment (rcallen89) [inline app/javascript/packs/homePage.jsx:133]: Same InstantClick change

File: app/javascript/packs/relatedVideos.jsx [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+
+function loadVideos() {
+  const root = document.getElementById('videos-container');
+  render(
+    <RelatedVideos videos={root.dataset.videos} />,
+    root,
+    root.firstElementChild,
+  );
+}
+
```
Comment (rcallen89) [inline app/javascript/packs/relatedVideos.jsx:12]: Original Comment from Jonathan:
defines a function that will render the RelatedVideos component to the page when called by javascript_pack_tags

File: app/javascript/packs/relatedVideos.jsx [hunk 7]
```diff
@@ -0,0 +1,20 @@
...
+document.ready.then(() => {
+  loadVideos();
+  window.InstantClick.on('change', () => {
+    if (document.getElementById('videos-container')) {
+      loadVideos();
+    }
+  });
+});
```
Comment (rcallen89) [inline app/javascript/packs/relatedVideos.jsx:20]: This calls our loadVideo function and also preloads it with instant click

File: app/javascript/relatedVideos/RelatedVideos.jsx [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+import PropTypes from 'prop-types';
+import { VideoPlayer } from './components/videoPlayer';
+
+export const RelatedVideos = ({ videos }) => (
+  <div>
+    <h1>Related Videos</h1>
+    <div className="related-videos">
+      {JSON.parse(videos).map(video => (
+        <VideoPlayer videoId={video} />
+      ))}
```
Comment (rcallen89) [inline app/javascript/relatedVideos/RelatedVideos.jsx:11]: Original comment from Jonathan
Since they pass props via the data set, they all come in as strings, so this parses it back out and iterates over an array of video IDs creating a VideoPlayer component for each one

File: app/controllers/stories_controller.rb (hunk 3 above)
Comment (KellyIB) [reply app/controllers/stories_controller.rb:225]: I think that expiration is perfect.

Comment (KellyIB) [reply app/controllers/stories_controller.rb:225]: I think the expiration length is perfect.

**Review by KellyIB — APPROVED** [review]
Caching looks great, nice that you pulled out the related videos method  from the decorator.
